### ISSUE TITLE
can't use in pop-up box？？

### ISSUE THREAD

**Issue by goodking-bq** [FE-Mars/monaco-editor-vue#27]
when i use it in dialog in vuetify,it can't  render,

**Comment by FE-Mars** [comment]
@goodking-bq Check if the pop-up box is not added to the HTML and the height acquisition fails

**Comment by goodking-bq** [comment]
> @goodking-bq Check if the pop-up box is not added to the HTML and the height acquisition fails

function initMonaco in $nexttick  can fix it.

**Comment by FE-Mars** [comment]
No, it should be fixed in your project

**Comment by Lavhe** [comment]
I am still having this issue on Vuetify, where the code editor does not render on a dialog

@goodking-bq how did you resolve this?

**Comment by goodking-bq** [comment]
> I am still having this issue on Vuetify, where the code editor does not render on a dialog
> 
> @goodking-bq how did you resolve this?
change this code to 
https://github.com/FE-Mars/monaco-editor-vue/blob/4a54983f231a2b8041fd5bce26041a8e3cb2811c/src/index.js#L65

```
  this.$nextTick(function(){
   this.init...
})
```
