### ISSUE TITLE
Syntax highlighting does not work

### ISSUE THREAD

**Issue by Symbolk** [FE-Mars/monaco-editor-vue#3]
Sorry to bother again, but I found that the syntax hightlignting does not work for me, either in normal editor and diffeditor. :-(

**Comment by FE-Mars** [comment]
language the initial language of the auto created model in the editor. Defaults to javascript.

**Comment by Symbolk** [comment]
> language the initial language of the auto created model in the editor. Defaults to javascript.

It should be, but I cannot see colors, here is my sample code:  https://github.com/Symbolk/vue-monaco-test. I tried 2 libs in this project, but both do not properly highlight the code.

Thanks for any help!

Ref: Another lib : https://github.com/egoist/vue-monaco

**Comment by FE-Mars** [comment]
I fixed this problem

**Comment by Symbolk** [comment]
> I fixed this problem

Thanks for the effort! I upgraded the dependency to the latest 1.0.7 with `yarn upgrade`, but still see no highlighting when running with `yarn serve`. Can you have a look at my test repo? I cannot see what's going wrong.

https://github.com/Symbolk/vue-monaco-test

**Comment by FE-Mars** [comment]
You should use vue.config.js
[Working with Webpack
#](https://cli.vuejs.org/zh/guide/webpack.html)
